runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: homegreenwebsite/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto


default_expiration: "1m"