runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: homegreenwebsite/static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

beta_settings:
  cloud_sql_instances: h0m3gr33n:europe-west3:homegreenfresh

default_expiration: "1m"